version: '3.8'

services:
  codeceptjs-tests:
    build: .
    container_name: codeceptjs-api-tests
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - NODE_ENV=test
    volumes:
      - ./output:/app/output
      - ./test-results:/app/test-results
    command: npm run test:ci
    networks:
      - test-network

  # Service for running specific test suites
  youtube-tests:
    build: .
    container_name: youtube-api-tests
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    volumes:
      - ./output:/app/output
    command: npm run test:youtube
    networks:
      - test-network
  
  github-tests:
    build: .
    container_name: github-api-tests
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    volumes:
      - ./output:/app/output
    command: npm run test:github
    networks:
      - test-network
  
  jsonplaceholder-tests:
    build: .
    container_name: jsonplaceholder-api-tests
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    volumes:
      - ./output:/app/output
    command: npm run test:jsonplaceholder
    networks:
      - test-network
  
  countries-tests:
    build: .
    container_name: countries-api-tests
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    volumes:
      - ./output:/app/output
    command: npm run test:countries
    networks:
      - test-network
  
  all-api-tests:
    build: .
    container_name: all-api-tests
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    volumes:
      - ./output:/app/output
    command: npm run test:all-apis
    networks:
      - test-network


networks:
  test-network:
    driver: bridge
